package pojo;

public class SysSchedule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_schedule.sid
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_schedule.uid
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_schedule.title
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_schedule.completed
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    private Integer completed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_schedule.sid
     *
     * @return the value of sys_schedule.sid
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_schedule.sid
     *
     * @param sid the value for sys_schedule.sid
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_schedule.uid
     *
     * @return the value of sys_schedule.uid
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_schedule.uid
     *
     * @param uid the value for sys_schedule.uid
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_schedule.title
     *
     * @return the value of sys_schedule.title
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_schedule.title
     *
     * @param title the value for sys_schedule.title
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_schedule.completed
     *
     * @return the value of sys_schedule.completed
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    public Integer getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_schedule.completed
     *
     * @param completed the value for sys_schedule.completed
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    public void setCompleted(Integer completed) {
        this.completed = completed;
    }
}