package mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pojo.SysSchedule;
import pojo.SysScheduleExample;

public interface SysScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    int countByExample(SysScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    int deleteByExample(SysScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    int insert(SysSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    int insertSelective(SysSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    List<SysSchedule> selectByExample(SysScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    SysSchedule selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    int updateByExampleSelective(@Param("record") SysSchedule record, @Param("example") SysScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    int updateByExample(@Param("record") SysSchedule record, @Param("example") SysScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    int updateByPrimaryKeySelective(SysSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_schedule
     *
     * @mbggenerated Mon Dec 11 15:22:01 CST 2023
     */
    int updateByPrimaryKey(SysSchedule record);
}